version: "3"
services:
  frontend:
    environment: 
      REACT_APP_API_URL: "http://192.168.99.100:3100" # uses docker toolbox url
      CHOKIDAR_USEPOLLING: "true" # allows live reload for docker toolbox
